version: "3"
services:
    nginx:
      image: nginx
      container_name: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
      networks:
        - backbone

    httpd-1:
      container_name: httpd-1
      image: httpd:2.4
      networks:
        - backbone
      expose: 
        - 8080

    httpd-2:
      container_name: httpd-2
      image: httpd:2.4
      networks:
        - backbone
      expose: 
        - 8080

networks:
  backbone:
    driver: bridge