version: "3"

volumes:
  prom_data: {}

services:
  nginx:
    image: nginx
    restart: unless-stopped
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - hackathon-api

  hackathon-frontend:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./frontend/index.html:/usr/local/apache2/htdocs/index.html

  hackathon-api:
    image: hackathon-api
    build:
      context: ./Dockerfile
    restart: unless-stopped
    deploy:
      replicas: 1
    ports:
      - 80:5000
