version: "3"
services:
    nginx:
      image: nginx
      restart: unless-stopped
      container_name: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - "80:80"
      networks:
        - backbone

    api:
      image: hackathon-api
      restart: unless-stopped
      build:
        context: ./Dockerfile
      deploy:
        replicas: 2
      expose: 
        - 8080
      networks:
        - backbone

networks:
  backbone:
    driver: bridge